---
version: "3.4"

services:
  traefik:
    image: traefik:2.2
    restart: always
    ports:
      - 8080:80
      - 8443:443
    volumes:
    - ./traefik:/etc/traefik/
  nginx:
    image: nginx
    ports:
      - 8081:80
      - 8444:443
    volumes:
    - ./nginx:/etc/nginx/
  traefikv1:
    image: traefik:1.7
    restart: always
    ports:
      - 8082:80
      - 8445:443
    volumes:
    - ./traefikv1:/etc/traefik/

  h2cbackend:
    build: ./h2cbackend
